# ┌────────────────────────────────────────────────────────────────────────────┐
# │ Folder Structure on GitHub Runner                                          │
# │                                                                            │
# │ GitHub Actions checks out your repo into:                                  │
# │   /home/runner/work/<repo-name>/<repo-name>/                               │
# │                                                                            │
# │ After both checkouts:                                                      │
# │                                                                            │
# │ /home/runner/work/SampleDotnetframework47MVC/                              │
# │ ├── app/                          # ⬅ your app repo                        │
# │ │   └── infrastructure/           #    contains main.bicep                 │
# │ │       └── main.bicep                                                   │
# │ ├── shared-bicep/                 # ⬅ shared modules repo                  │
# │ │   └── modules/appservice/       #    shared appservice.bicep module      │
# │ │       └── appservice.bicep                                              │
# └────────────────────────────────────────────────────────────────────────────┘

name: Reusable Bicep Deploy Workflow

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      resource_group_name:
        required: true
        type: string
    secrets:
      azure_credentials:
        required: true
      repo_token:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout shared infrastructure modules repo
      - name: Checkout shared Bicep modules
        uses: actions/checkout@v4
        with:
          repository: aaggarwalppwfm/biceps
          path: shared-bicep
          token: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Checkout the caller (app) repo under ./app
      - name: Checkout calling app repo
        uses: actions/checkout@v4
        with:
          path: app
          
      - name: List folder contents for sanity check
        run: |
          echo "Listing root:"
          ls -la
          echo "Listing app/infrastructure:"
          ls -la app/infrastructure
          echo "Listing shared-bicep:"
          ls -la shared-bicep/modules

      # ✅ Azure Login using service principal credentials from caller
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure_credentials }}

      # ✅ Deploy Bicep template by calling the composite action
      - name: Deploy Azure Resources (via shared action)
        uses: ./shared-bicep/.github/actions/deploy-infra
        with:
          resource_group: ${{ inputs.resource_group_name }}
          environment_name: ${{ inputs.env }}
          app_working_dir: ./app

      # ✅ Generate metadata file with context info (commit, branch, URL, etc.)
      - name: Create Deployment Metadata
        working-directory: ./app
        run: |
          echo "Deployed commit: ${{ github.sha }}" > deployment-info.txt
          echo "Environment: ${{ inputs.env }}" >> deployment-info.txt
          echo "Branch: ${{ github.ref }}" >> deployment-info.txt
          echo "Run number: ${{ github.run_number }}" >> deployment-info.txt
          echo "Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> deployment-info.txt

      # ✅ Upload deployment metadata as artifact
      - name: Upload Deployment Metadata
        uses: actions/upload-artifact@v4
        with:
          name: deployment-metadata-${{ inputs.env }}-${{ github.run_number }}
          path: ./app/deployment-info.txt

      # ✅ Create a tag for the deployment in the git repo
      - name: Create Git Tag for Deployment
        working-directory: ./app
        env:
          GH_TOKEN: ${{ secrets.repo_token }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch --all
          git tag deploy-${{ inputs.env }}-v${{ github.run_number }}
          git push https://x-access-token:${GH_TOKEN}@github.com/aaggarwalppwfm/SampleDotnetframework47MVC.git deploy-${{ inputs.env }}-v${{ github.run_number }}
