# ┌────────────────────────────────────────────────────────────────────────────┐
# │ Folder Structure on GitHub Runner                                          │
# │ checkout caller repo                                                       │
# │ /home/runner/work/SampleDotnetframework47MVC/                             │
# │ ├── SampleDotnetframework47MVC/        # ⬅ your app repo (checked out by   │
# │ │   ├── infrastructure/                #    default GitHub Actions         │
# │ │   │   └── main.bicep                 #    contains main deployment logic │
# │ │   └── .github/                       #    holds workflows                │
# │   
# │ checkout shared repo
# │ ├── biceps/                            # ⬅ shared Bicep modules repo       │
# │ │   └── modules/                       #    checked out with path: biceps  │
# │ │       └── appservice/                                                   │
# │ │           └── appservice.bicep                                           │
# └────────────────────────────────────────────────────────────────────────────┘


name: Reusable Bicep Deploy Workflow

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      resource_group_name:
        required: true
        type: string
    secrets:
      azure_credentials:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4

      - name: Checkout shared Bicep repo
        uses: actions/checkout@v4
        with:
          repository: aaggarwalppwfm/biceps
          path: biceps
          token: ${{ secrets.GITHUB_TOKEN }}  

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Deploy Azure Resources (via shared action)
        uses: ./biceps/.github/actions/deploy-infra  
        with:
          resource_group: ${{ inputs.resource_group_name }}
          environment_name: ${{ inputs.env }}

      - name: Create Deployment Metadata
        run: |
          echo "Deployed commit: ${{ github.sha }}" > deployment-info.txt
          echo "Environment: ${{ inputs.env }}" >> deployment-info.txt
          echo "Branch: ${{ github.ref }}" >> deployment-info.txt
          echo "Run number: ${{ github.run_number }}" >> deployment-info.txt
          echo "Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> deployment-info.txt

      - name: Upload Deployment Metadata
        uses: actions/upload-artifact@v4
        with:
          name: deployment-metadata-${{ inputs.env }}-${{ github.run_number }}
          path: deployment-info.txt

      - name: Create Git Tag for Deployment
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch --all
          git tag deploy-${{ inputs.env }}-v${{ github.run_number }}
          git push origin deploy-${{ inputs.env }}-v${{ github.run_number }}
