# .github/workflows/bicep_deploy_reusable.yml

name: Reusable Bicep Deploy Workflow

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      resource_group_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resources (Bicep)
        run: |
          echo "Starting Bicep deployment for environment: ${{ inputs.env }}"

          az deployment group create \
            --name ${{ inputs.env }}-deployment-${{ github.run_number }} \
            --resource-group ${{ inputs.resource_group_name }} \
            --template-file infrastructure/main.bicep \
            --parameters infrastructure/environments/${{ inputs.env }}.bicepparam \
            --verbose

          echo "Bicep deployment completed."

      - name: Create Deployment Metadata
        if: ${{ inputs.env == 'prod' }}
        run: |
          echo "Deployed commit: ${{ github.sha }}" > deployment-info.txt
          echo "Environment: prod" >> deployment-info.txt
          echo "Branch: ${{ github.ref }}" >> deployment-info.txt
          echo "Run number: ${{ github.run_number }}" >> deployment-info.txt
          echo "Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> deployment-info.txt

      - name: Upload Deployment Metadata
        if: ${{ inputs.env == 'prod' }}
        uses: actions/upload-artifact@v4
        with:
          name: deployment-metadata
          path: deployment-info.txt

      - name: Create Git Tag for Production Deployment
        if: ${{ inputs.env == 'prod' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch --all
          git tag deploy-v${{ github.run_number }}
          git push origin deploy-v${{ github.run_number }}
